# Generated by Django 6.0.5 on 2026-05-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='printed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='receipt',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='receipt',
            table='receipts',
        ),
    ]
