# Generated by Django 6.0.5 on 2026-05-20 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return',
            name='return_type',
            field=models.CharField(choices=[('full', 'Full Return'), ('partial', 'Partial Return'), ('exchange', 'Exchange')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
