# Generated by Django 6.0.5 on 2026-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_return_created_at_return_return_type_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
