# Generated by Django 6.0.5 on 2026-05-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_return_updated_at'),
        ('sales', '0002_alter_sale_options_sale_notes_sale_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='direction',
            field=models.CharField(choices=[('customer', 'Customer Return (add stock)'), ('supplier', 'Supplier Return (remove stock)')], default='customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
